const cheapestPicksEmailList = require('./cheapest-picks-email-list');
const cheapestPicksEmailObj = cheapestPicksEmailList
    .reduce((acc, val) => ({
        ...acc,
        [val]: 'cheapest-picks-chp50--4'
    }), {});

const {
    creme,
    moderates,
    occasionals,
    occasionalLowCount,
    keepAnEyeOn,
    allShorts
} = require('./pms/manual');



// TODO: flatten list of strategies with PMs for emailObj same way as forPurchase
module.exports = {
    // important settings
    sellAllStocksOnNthDay: 1,
    purchaseAmt: 50,
    forPurchase: [

        // anycountperfectos from spm
        "constant-risers-10minute-percUpHighClosePoints-filtered70-100",
        "sudden-drops-last30trend-first1-400",
        "sudden-drops-last2trend-first1--30",
        "sudden-drops-last3trend-filter10-100",
        "constant-risers-10minute-percUpHighClosePoints-filtered80-fiveTo10-40",
        "sudden-drops-last2trend-first2-400",
        "sudden-drops-last3trend-first2-500",
        "based-on-jump-down8overnight-trending53-gt500kvolume-first1-fiveTo10-0",
        "fizbiz-nanoEarlyRunners-first1-380",
        "sudden-drops-last10trend-first1-fiveTo10-470",
        "sudden-drops-last10trend-first2-fiveTo10--50",
        "based-on-jump-gtEightOvernight-trending103-notWatchout-gtneg20percmax-30",
        "sudden-drops-last5trend-first1--50",
        "sudden-drops-last5trend-filter10-400",
        "sudden-drops-last10trend-first1-500",
        "sudden-drops-last5trend-first1-fiveTo10--30",
        "sudden-drops-last18trend-filter30-280",
        "based-on-jump-down3overnight-trending35257-notWatchout-ltneg50percmax-fiveTo10-30",
        "low-float-high-volume-volTo2WeekPoints-trendgt30-tenTo15-384",
        "low-float-high-volume-absVolPoints-trendgt30-tenTo15-384",
        "low-float-high-volume-floatTimesvolToAvgPoints-trendgt30-tenTo15-384",
        "low-float-high-volume-floatTimesfloatToVolume-trendgt30-tenTo15-384",
        "low-float-high-volume-twoWeekVolToAvgPoints-trendgt30-tenTo15-384",
        "low-float-high-volume-floatPoints-trendgt30-tenTo15-384",
        "constant-risers-10minute-percUpCloseOnlyPoints-filtered70-198",
        "constant-risers-10minute-percUpHighClose-filtered70-198",
        "low-float-high-volume-floatTimesabsVolPoints-trenddowngt30-tenTo15-315",
        "low-float-high-volume-volToAvgPoints-trenddowngt30-notWatchout-tenTo15-315",
        "low-float-high-volume-floatTimesvolTo2WeekPoints-trenddowngt30-notWatchout-tenTo15-315",
        "low-float-high-volume-floatTimesfloatToVolume-trenddowngt30-notWatchout-tenTo15-315",
        "low-float-high-volume-floatTimestwoWeekVolToAvgPoints-trenddowngt30-tenTo15-315",
        "sudden-drops-last18trend-filter10-tenTo15-360",
        "sudden-drops-last18trend-first1-fiveTo10-500",
        "sudden-drops-last10trend-first2-tenTo15-500",
        "sudden-drops-last50trend-first1-tenTo15-430",
        "based-on-jump-down3overnight-trending53-gt1milvolume-first3-fiveTo10-5",
        "based-on-jump-down8overnight-trending103-notWatchout-first1-tenTo15-30",
        "low-float-high-volume-floatTimesabsVolPoints-trendgt30-shouldWatchout-tenTo15-384",
        "low-float-high-volume-floatTimestwoWeekVolToAvgPoints-trendgt40-shouldWatchout-tenTo15-384",
        "low-float-high-volume-floatTimesabsVolPoints-trendgt40-tenTo15-384",
        "low-float-high-volume-volToAvgPoints-trendgt40-shouldWatchout-tenTo15-384",
        "low-float-high-volume-floatTimesfloatToVolume-trendgt40-shouldWatchout-tenTo15-384",
        "low-float-high-volume-volToAvgPoints-trendgt40-tenTo15-384",
        "sudden-drops-last1trend-first1-tenTo15--10",
        "constant-risers-5minute-percUpCloseOnlyPoints-filtered70-fiveTo10-40",
        "sudden-drops-last30trend-filter10-fifteenTo20-360",
        "based-on-jump-down8overnight-trending53-gt1milvolume-fiveTo10-16",
        "based-on-jump-gtEightOvernight-trending103-shouldWatchout-first1-fifteenTo20-16",
        "based-on-jump-gtEightOvernight-trending53-notWatchout-first1-tenTo15-0",
        "sudden-drops-last50trend-filter10-tenTo15-400",
        "based-on-jump-down8overnight-trending53-notWatchout-ltneg50percmax-first3-5",
        "based-on-jump-down8overnight-trending103-notWatchout-ltneg50percmax-16",
        "based-on-jump-gtEightOvernight-trending607-shouldWatchout-fifteenTo20-30",
        "based-on-jump-gtEightOvernight-trending53-gt100kvolume-first2-tenTo15-0",
        "sudden-drops-last1trend-first2--10",
        "spread-singleLargestSpreadPerc100kVolume-tenTo15-202",
        "constant-risers-10minute-percUpHighClosePoints-filtered70-fifteenTo20-80",
        "based-on-jump-gtEightOvernight-trending53-shouldWatchout-first3-tenTo15-0",
        "low-float-high-volume-absVolPoints-trenddowngt20-fifteenTo20-384",
        "low-float-high-volume-floatTimesfloatToVolume-trenddowngt20-fifteenTo20-384",
        "low-float-high-volume-floatTimesvolToAvgPoints-trenddowngt20-fifteenTo20-384",
        "low-float-high-volume-twoWeekVolToAvgPoints-trenddowngt20-fifteenTo20-384",
        "low-float-high-volume-floatPoints-trenddowngt20-fifteenTo20-384",
        "low-float-high-volume-floatTimesvolTo2WeekPoints-trenddowngt30-tenTo15-276",
        "low-float-high-volume-floatPoints-trenddowngt30-tenTo15-276",
        "based-on-jump-down8overnight-trending607-gt500kvolume-first2-tenTo15-0",
        "constant-downers-5minute-percDownLowClosePoints-filtered70-fifteenTo20-242",
        "based-on-jump-fourToEightOvernight-trending103-gt100kvolume-first1-fifteenTo20-5",
        "sudden-drops-last18trend-filter10-fifteenTo20-328",
        "sudden-drops-last30trend-filter10-fiveTo10-500",
        "sudden-drops-last5trend-first1-fifteenTo20--30",
        "sudden-drops-last50trend-filter20-tenTo15-280",
        "based-on-jump-down3overnight-trending103-gt100kvolume-first1-fifteenTo20-0",
        "spread-bidAskLastTradeSame-202",
        "constant-risers-10minute-percUpHighClose-filtered70-fiveTo10-250",
        "based-on-jump-down5overnight-trending103-gt1milvolume-first1-fiveTo10-0",
        "low-float-high-volume-floatTimesabsVolPoints-trenddowngt20-shouldWatchout-fiveTo10-95",
        "low-float-high-volume-floatTimestwoWeekVolToAvgPoints-trenddowngt20-shouldWatchout-fiveTo10-95",
        "low-float-high-volume-floatTimesfloatToVolume-trenddowngt20-shouldWatchout-fiveTo10-95",
        "low-float-high-volume-floatTimesvolToAvgPoints-trendgt20-notWatchout-tenTo15-150",
        "based-on-jump-gtEightOvernight-trending53-gt1milvolume-first1-tenTo15-16",
        "based-on-jump-down8overnight-trending35257-gt1milvolume-first1-fiveTo10-30",
        "low-float-high-volume-volTo2WeekPoints-trendgt40-shouldWatchout-tenTo15-276",
        "low-float-high-volume-floatPoints-trendgt40-shouldWatchout-tenTo15-276",
        "low-float-high-volume-floatTimestwoWeekVolToAvgPoints-trendgt40-tenTo15-276",
        "based-on-jump-fourToEightOvernight-trending103-notWatchout-ltneg50percmax-fiveTo10-5",
        "low-float-high-volume-floatTimestwoWeekVolToAvgPoints-trendgt20-notWatchout-fiveTo10-150",
        "low-float-high-volume-floatTimesabsVolPoints-trendgt20-notWatchout-fiveTo10-150",
        "low-float-high-volume-floatTimestwoWeekVolToAvgPoints-trenddowngt20-notWatchout-fifteenTo20-384",
        "low-float-high-volume-floatTimesabsVolPoints-trenddowngt20-notWatchout-fifteenTo20-384",
        "low-float-high-volume-volToAvgPoints-trenddowngt20-notWatchout-fifteenTo20-384",
        "based-on-jump-gtEightOvernight-trending53-gt100kvolume-first1-fifteenTo20-0",
        "based-on-jump-fourToEightOvernight-trending53-gt500kvolume-first2-fifteenTo20-16",
        "low-float-high-volume-absVolPoints-trendgt20-notWatchout-fifteenTo20-150",
        "based-on-jump-down8overnight-trending35257-gt500kvolume-tenTo15-0",
        "constant-risers-10minute-percUpCloseOnly-filtered80-fiveTo10-100",
        "based-on-jump-down3overnight-trending35257-gt1milvolume-fiveTo10-5",
        "based-on-jump-down8overnight-trending607-gt1milvolume-first1-tenTo15-0",
        "low-float-high-volume-absVolPoints-trenddowngt30-fiveTo10-150",
        "based-on-jump-gtEightOvernight-trending103-gt500kvolume-tenTo15-5",
        "constant-risers-10minute-percUpHighClose-filtered70-tenTo15-140",
        "low-float-high-volume-floatTimesabsVolPoints-trenddowngt20-fifteenTo20-276",
        "low-float-high-volume-volTo2WeekPoints-trenddowngt20-fifteenTo20-276",
        "low-float-high-volume-floatTimesfloatToVolume-trenddowngt20-notWatchout-fifteenTo20-276",
        "low-float-high-volume-floatTimesvolTo2WeekPoints-trenddowngt20-notWatchout-fifteenTo20-276",
        "low-float-high-volume-floatPoints-trenddowngt20-notWatchout-fifteenTo20-276",

        
        // sudden-drops
        'sudden-drops-last3trend-filter10-100',
        'sudden-drops-last3trend-filter10-189',
        'sudden-drops-last10trend-filter10--10',
        'sudden-drops-last2trend-filter10-100',
        'sudden-drops-last5trend-filter10-400',
        'sudden-drops-last30trend-filter10-tenTo15-221',
        'sudden-drops-last30trend-filter10-400',
        'sudden-drops-last1trend-filter10-221',
        'sudden-drops-last50trend-filter10-400',
        'sudden-drops-last1trend-filter10-fiveTo10-14',
        'sudden-drops-last2trend-filter10-221',
        'sudden-drops-last3trend-filter10-221',
        'sudden-drops-last18trend-filter10-fifteenTo20-290',
        'sudden-drops-last18trend-filter10-tenTo15-360',
        'sudden-drops-last18trend-filter10-tenTo15-221',
        'sudden-drops-last10trend-filter10-fifteenTo20-290',
        'sudden-drops-last50trend-filter10-tenTo15-400',
        'sudden-drops-last30trend-filter10-fifteenTo20-360',
        'sudden-drops-last18trend-filter10-fifteenTo20-328',
        'sudden-drops-last30trend-filter10-fiveTo10-500',
        'sudden-drops-last50trend-filter10-fiveTo10-500',
        'sudden-drops-last10trend-filter10-tenTo15-221',
        'sudden-drops-last5trend-filter10--10',
        'sudden-drops-last18trend-filter10--10',
        'sudden-drops-last18trend-filter10-tenTo15-290',
        'sudden-drops-last10trend-filter10-fifteenTo20-328',
        'sudden-drops-last10trend-filter10-fifteenTo20-63',
        'sudden-drops-last30trend-filter10-tenTo15-388',
        'sudden-drops-last1trend-filter10-360',
        'sudden-drops-last50trend-filter10-tenTo15-470',
        'sudden-drops-last50trend-filter20-tenTo15-280',
        'sudden-drops-last30trend-filter10-fifteenTo20-280',
        'sudden-drops-last18trend-filter10-fifteenTo20-280',
        'sudden-drops-last10trend-filter10-tenTo15-360',

        // constant-risers
        'constant-risers-10minute-percUpCloseOnlyPoints-filtered70-100',
        'constant-risers-10minute-percUpHighClosePoints-filtered70-100',
        'constant-risers-10minute-percUpHighClosePoints-filtered80-fiveTo10-40',
        'constant-risers-10minute-percUpCloseOnlyPoints-filtered80-fiveTo10-40',
        'constant-risers-10minute-percUpHighClosePoints-filtered70-198',
        'constant-risers-10minute-percUpCloseOnlyPoints-filtered70-198',
        'constant-risers-10minute-percUpHighClose-filtered70-198',
        'constant-risers-5minute-percUpCloseOnlyPoints-filtered70-fiveTo10-40',
        'constant-risers-10minute-percUpCloseOnlyPoints-filtered70-fiveTo10-40',
        'constant-risers-10minute-percUpCloseOnlyPoints-filtered70-fifteenTo20-80',
        'constant-risers-10minute-percUpHighClosePoints-filtered70-fifteenTo20-80',
        'constant-risers-10minute-percUpHighClose-filtered70-fiveTo10-250',
        'constant-risers-10minute-percUpHighClosePoints-filtered70-fiveTo10-250',
        'constant-risers-10minute-percUpCloseOnlyPoints-filtered70-fiveTo10-250',
        'constant-risers-10minute-percUpCloseOnly-filtered70-fiveTo10-250',
        'constant-risers-10minute-percUpCloseOnlyPoints-filtered70-tenTo15-140',
        'constant-risers-10minute-percUpHighClosePoints-filtered70-tenTo15-140',
        'constant-risers-10minute-percUpCloseOnly-filtered80-fiveTo10-100',
        'constant-risers-10minute-percUpHighClose-filtered80-fiveTo10-100',
        'constant-risers-10minute-percUpHighClose-filtered70-tenTo15-140'
    ],
    fallbackSellStrategy: 'limit3',
    force: {
        sell: [
            'FIHD'
        ],
        keep: [
            // 'NSPR',
            // 'BOXL',
            // 'SEII',
            // 'AWX'
        ]
    },

    // email
    email: {
        [['chief', 'sm', 'urph', '@', 'gm', 'ail', '.com'].join('')]: [
            // ...allShorts
        ],
        ...cheapestPicksEmailObj
    }
};
